config/routes.rb
CarmenGallery::Application.routes.draw do

  resources :artworks
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:new, :create, :destroy]
  
  match ':controller/:id/:action(.:format)'
  match '/artworks', :to => 'artworks#index'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  root :to => 'pages#home'
  match '/drawings', :to => 'pages#drawings'
  match '/statement', :to => 'pages#statement'
  match '/paintings', :to => 'pages#paintings'
  match '/prints', :to => 'pages#prints'
  match '/objects', :to => 'pages#objects'
  match '/about', :to => 'pages#about'
  

end

app/models/artwork.rb
# == Schema Information
# Schema version: 20110407011032
#
# Table name: artworks
#
#  id                  :integer(4)      not null, primary key
#  name                :string(255)
#  art                 :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer(4)
#  avatar_updated_at   :datetime
#  email               :string(255)
#  avatar_file         :binary(21474836
#  avatar_small_file   :binary(21474836
#  avatar_thumb_file   :binary(21474836
#

class Artwork < ActiveRecord::Base
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  #has_many :microposts, :dependent => :destroy
  
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }
  validates :art, :presence => true
  
  has_attached_file :avatar,
                    :storage => :database,
                    :styles => {:thumb => "75x75>", :small => "400x400>"},
                    #:path => ':rails_root/nonpublic/system/:attachment/:id/:style/:basename.:extension',
                    :url => '/:class/:id/:attachment?style=:style'
  default_scope select_without_file_columns_for(:avatar)

end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  downloads_files_for :artwork, :avatar
  
  # GET /artworks
  # GET /artworks.xml
  def index
    @artworks = Artwork.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @artworks }
    end
  end

  # GET /artworks/1
  # GET /artworks/1.xml
  def show
    @artwork = Artwork.find(params[:id])
    $current_artwork = @artwork
    #@microposts = @artwork.microposts.paginate(:page => params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @artwork }
    end
  end

  # GET /artworks/new
  # GET /artworks/new.xml
  def new
    @artwork = Artwork.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @artwork }
    end
  end

  # GET /artworks/1/edit
  def edit
    @artwork = Artwork.find(params[:id])
  end

  # POST /artworks
  # POST /artworks.xml
  def create
    @artwork = Artwork.new(params[:artwork])

    respond_to do |format|
      if @artwork.save
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully created.') }
        format.xml  { render :xml => @artwork, :status => :created, :location => @artwork }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /artworks/1
  # PUT /artworks/1.xml
  def update
    @artwork = Artwork.find(params[:id])

    respond_to do |format|
      if @artwork.update_attributes(params[:artwork])
        format.html { redirect_to(@artwork, :notice => 'Artwork was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @artwork.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /artworks/1
  # DELETE /artworks/1.xml
  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy

    respond_to do |format|
      format.html { redirect_to(artworks_url) }
      format.xml  { head :ok }
    end
  end
  
  def avatars
    artwork = Artwork.find(params[:id])
    style = params[:style]?params[:style] : 'original'
    #send_file artwork.avatar.path(style), :type => artwork.avatar_content_type
    send_data artwork.avatar.file_contents(style), :type => artwork.avatar_content_type
  end
  
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artworks/_form.html.erb
<%= form_for(@artwork, :html => { :multipart => true }) do |f| %>
  <% if @artwork.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
      <% @artwork.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :email, "Artwork Id (email)" %><br />
	<%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :art %><br />
    <%= f.select :art, options_for_select(["painting", "drawing", "print", "tshirt", "object"]), :class => "select" %>
  </div>
  <div class="field">
  	<%= f.label :avatar, "Artwork' image" %><br />
	<%= f.file_field :avatar, :class => "upload" %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Save Artwork", :class => "button" %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Editing artwork</h1>

<%= render 'form' %>

<%= link_to 'Show', @artwork %> |
<%= link_to "Back to Artwork's Administration", artworks_path %>

app/views/artworks/index.html.erb
<h1>Listing Artworks</h1>

<table>
  <tr>
    <th>Artwork</th>
	<th>Name</th>
    <th>Art</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artworks.each do |artwork| %>
  <tr>
    <td><%= image_tag artwork.avatar.url(:thumb) %></td>
	<td><%= artwork.name %></td>
    <td><%= artwork.art %></td>
    <td><%= link_to 'Show', artwork %></td>
    <td><%= link_to 'Edit', edit_artwork_path(artwork) %></td>
    <td class="actions"><%= button_to 'Delete', artwork, :method => :delete, :confirm => "Are you sure?", :class => "button" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artwork', new_artwork_path %>

app/views/artworks/new.html.erb
<h1>New artwork</h1>

<%= render 'form' %>

<%= link_to 'Back', artworks_path %>

app/views/artworks/show.html.erb
<h1>Showing Carmen's Artwork</h1>

<table class="artwork">
  <tr>
	<td class="main">
		<%= image_tag @artwork.avatar.url(:small) %>
	</td>
	<td class="sidebar round">
		<strong>Name: </strong>
		<%= @artwork.name %><br />
		<%= @artwork.art %><br />
	</td>
  </tr>
</table>

<% if signed_in? %>
<%= link_to "Edit", edit_artwork_path(@artwork) %> |
<%= link_to "Back to Artwork's Administration", artworks_path %>
<% else %>
<% if @artwork.art == 'painting' %><%= link_to "Back to Carmen's Paintings", paintings_path %><% end %>
<% if @artwork.art == 'drawing' %><%= link_to "Back to Carmen's Drawings", drawings_path %><% end %>
<% if @artwork.art == 'print' %><%= link_to "Back to Carmen's Prints", prints_path %><% end %>
<% if @artwork.art == 'tshirt' %><%= link_to "Back to Carmen's Objects", objects_path %><% end %>
<% if @artwork.art == 'object' %><%= link_to "Back to Carmen's Objects", objects_path %><% end %>
<% end %>