config/routes.rb
CarmenGallery::Application.routes.draw do

  resources :artworks
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:new, :create, :destroy]
  
  match ':controller/:id/:action(.:format)'
  match '/artworks', :to => 'artworks#index'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  root :to => 'pages#home'
  match '/drawings', :to => 'pages#drawings'
  match '/statement', :to => 'pages#statement'
  match '/paintings', :to => 'pages#paintings'
  match '/prints', :to => 'pages#prints'
  match '/objects', :to => 'pages#objects'
  match '/about', :to => 'pages#about'
  

end

app/models/user.rb
# == Schema Information
# Schema version: 20110425231210
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean(1)
#

require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :format => { :with => email_regex }, 
                    :uniqueness => { :case_sensitive => false }
  # Automatically creates virtual attribute password_confirmation
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }
  
  before_save :encrypt_password
  
  def has_password?(submitted_password)
    # Returns true if user's password = submitted password
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password) #Class method identify with self
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    return nil if user.nil?
    return user if user.salt == cookie_salt
  end
  
  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end
  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end
  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter arranges a call to a method before an action
  before_filter :authenticate, :only => [:edit, :update, :index, :destroy]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  
  def index
    @title = "Administrators"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Carmen's Gallery"
      redirect_to user_path(@user)
    else
      @title = "Sign up"
      render 'new'  
    end
  end
  
  def edit
    @title = "Edit user"
  end
   
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Administrator updated"
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Administrator deleted"
    redirect_to users_path
  end
  
  private
    
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 75 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => "gravatar",
                                            :gravatar => options) 
  end
end

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user %>
	<%= link_to user.name, user %>
	<% if current_user.admin? %> | 
		<%= link_to "delete", user, :method => :delete, :confirm => "You sure?", :title => "Delete #{user.name}" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do|f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<br />
<div class="actions">
	<%= f.submit "Update", :class => "button" %>
</div>
<% end %>

<div>
	<%= gravatar_for @user%>
</div>

app/views/users/index.html.erb
<h1>All Administrators</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
		<%= render user %>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do|f| %>
<%= render 'shared/error_messages', :object => f.object %>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
	<%= f.label :email %><br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %><br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %><br />
	<%= f.password_field :password_confirmation %>
</div>
<br />
<div class="actions">
	<%= f.submit "Sign up", :class => "button" %>
</div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Administrator Information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</td>
		<td class="sidebar round">
			<%= link_to "Artwork's administration", artworks_path %>
			<%= link_to "Sign new admin Up!", signup_path %>
		</td>
	</tr>
</table>