config/routes.rb
CarmenGallery::Application.routes.draw do

  resources :artworks
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:new, :create, :destroy]
  
  match ':controller/:id/:action(.:format)'
  match '/artworks', :to => 'artworks#index'

  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signup', :to => 'users#new'
  root :to => 'pages#home'
  match '/drawings', :to => 'pages#drawings'
  match '/statement', :to => 'pages#statement'
  match '/paintings', :to => 'pages#paintings'
  match '/prints', :to => 'pages#prints'
  match '/objects', :to => 'pages#objects'
  match '/about', :to => 'pages#about'
  

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<% if signed_in? %>
			<li><%= link_to "Administrator index", users_path %></li>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Settings", edit_user_path(current_user)%></li>
			<% end %>
			<% if signed_in? %>
			<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
			<% else %>
				<% if current_page?(root_path) %>
					<li><%= link_to "Administrator Sign in", signin_path %></li>
				<% end %>
			<% end %>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Statement", statement_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Drawings", drawings_path %></li>
			<li><%= link_to "Paintings", paintings_path %></li>
			<li><%= link_to "Prints", prints_path %></li>
			<li><%= link_to "Objects", objects_path %></li>
		</ul>
	</nav>
	<br />
	<%= link_to logo, root_path %>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]> <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
<!--[if lt IE 8]> <%= stylesheet_link_tag 'blueprint/ie' %> <![endif]-->
<!--[if lt IE 7 ]> <html class="ie6">  <![endif]-->
<!--[if IE 7 ]>    <html class="ie7">  <![endif]-->
<!--[if IE 8 ]>    <html class="ie8">  <![endif]-->
<!--[if IE 9 ]>    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html class=""> <!--<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
	<head>
		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag :defaults %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header' %>
			<section class="round">
				<% flash.each do |key, value| %>
				<div class="flash <%= key %>">
					<%= value %>
				</div>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>